debug: ""
logstash_image: "t0ffel/logstash-kafka"
logstash_project: logstash-staging
production_elasticsearch: "http://elasticsearch.perf.lab.eng.bos.redhat.com:9280"
staging_elasticsearch: "http://elasticsearch.perf.lab.eng.bos.redhat.com:80"

# Index name prefixes for individual inputs
index_shipshift: "jenkins-staging2-logs"
index_collectd: "collectd"
index_log4j: "logstash"
index_lumberjack: "logstash"
job_name: logstash-job-1

configs_dir: "{{ role_path }}/files/"
# Define certs_dir to add certificates to the job
# certs_dir: "{{ role_path }}/files/"

ci_job_name: Interop-OSP_10-OCP_3.4-MLibVirt-HA-smoke-70e5f-stable-runtest
time_range_start_at: now-1d/d